### ISSUE TITLE
Priority endpoints required for MVP

### ISSUE THREAD

**Issue by Tryptophan** [gatsby-tv/westegg#29]
List of endpoints required for MVP:

**Comment by cjayross** [comment]
`/auth/signup`
`/auth/user/:id/exists`
`/auth/user/handle/:handle/exists`
`/auth/channel/handle/:handle/exists`

`/user/:id`
`/user/:id/feeds`
`/user/:id/subscription`
`/user/:id/promotion`
`/user/:id/handle`
`/user/:id/avatar`
`/user/:id/banner`

`/channel`
`/channel/:id`
`/channel/:id/content`
`/channel/:id/handle`
`/channel/:id/avatar`
`/channel/:id/banner`
`/channel/:id/poster`

`/video`
`/video/:id`
`/video/:id/view`

`/listing/featured/channels`
`/listing/videos/recommended`
`/listing/videos/popular`
`/listing/videos/new`
`/listing/subscriptions`
`/listing/topics`
